name: rtcloud
channels:
  - defaults
  - conda-forge
  - brainiak
dependencies:
  - awscli
  - bcrypt
  - brainiak
  - dcm2niix
  - flake8
  - inflect
  - ipython
  - jupyter
  - mypy
  - nibabel
  - nilearn
  - nodejs
  - numpy
  - openssl
  - pip
  - pydicom
  - pytest
  - requests
  - rpyc
  - scikit-learn
  - scipy
  - toml
  - tornado
  - websocket-client
  - wsaccel
  - pip:
    - pybids
    - watchdog
    - inotify
