name: rtcloud
channels:
  - defaults
  - conda-forge
dependencies:
  - awscli
  - bcrypt
  - boto3
  - dcm2niix
  - flake8
  - indexed_gzip  # for efficient random access of gzipped files with Nibabel
  - jupyter
  - mypy
  - nibabel
  - nilearn
  - nodejs
  - numpy
  - pip
  - pydicom
  - pytest
  - python=3.7
  - requests
  - rpyc
  - scipy
  - toml
  - tornado
  - websocket-client
  - wsaccel # for websocket acceleration
  - pip:
    - inotify
    - pybids
    - watchdog
