title = 'OpenNeuro Client'
# dsAccessionNumber = 'ds002338'
dsAccessionNumber = 'ds003524'
# subjectName = "xp201"
subjectName = "s01"
subjectDay = 1
runNum = [1]
scanNum = [1]

plotTitle = 'Realtime Plot'
plotXLabel = 'Volume #'
plotYLabel = 'Value'
plotAutoRangeX = true
plotAutoRangeY = true

