version: '3.3'
services:
  projectInterface:
    image: brainiak/rtcloud:latest
    container_name: rtserver
    command: tail -f /dev/null
    tty: true
    ports:
      - 8888:8888
    volumes:
      - certs:/rt-cloud/certs
      - /tmp/myproject:/rt-cloud/projects/myproject

volumes:
  certs: {}

