subjectNum = 908
subjectDay = 1
runNum = [ 1,]
numRuns = 3
dicomRoot = "None"
outRoot = "None"
dateString = 20230313
dicomNamePattern = "001_{RUN:06d}_{TR:06d}.dcm"
taskName = "feedback"
num_total_TRs = 270
num_runs_before_rt = 2
title = "functionalConnectivity"
scanNum = 1
minExpectedDicomSize = 300000
plotTitle = "Realtime feedback scores"
plotXLabel = "TR"
plotYLabel = "Feedback Yes/No"
plotXRangeLow = 0
plotXRangeHigh = 258
plotYRangeLow = -1
plotYRangeHigh = 2
plotAutoRangeX = true
plotAutoRangeY = false
demoStep = 0
dsAccessionNumber = "None"
