# Config file for sample.py project
title = 'Sample Project'
sessionId = "20180310T123000"
subjectName = "0219191_faceMatching"
# subjectName = "0301181_sample"
datestr = "20190219"
subjectNum = 101
subjectDay = 1
sessionNum = 1
runNum = [1]
scanNum = [13]
plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'Value'
plotXRangeLow = 0
plotXRangeHigh = 20
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = true

## important variables about the dicom files
dicomNamePattern = "001_0000{}_000{}.dcm"
minExpectedDicomSize = 300000