name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo $DOCKER_USER
        # docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    # - name: Build the Docker image
      # --tag my-image-name:$(date +%s)
      # run: docker build . --file docker/Dockerfile.rtcloud --tag brainiak/rtcloud:latest
  
    # - name: Docker Push
      # run: docker push brainiak/rtcloud:latest
