name: Make and Push Docker Images to Dockerhub

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2
      #echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin


    - name: docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        

    # - name: Build the Docker image
      # --tag my-image-name:$(date +%s)
      # run: docker build . --file docker/Dockerfile.rtcloud --tag brainiak/rtcloud:latest
  
    # - name: Docker Push
      # run: docker push brainiak/rtcloud:latest
