name: Make and Push Docker Images to Dockerhub

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        # echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} 

    # - name: Build the Docker image
      # --tag my-image-name:$(date +%s)
      # run: docker build . --file docker/Dockerfile.rtcloud --tag brainiak/rtcloud:latest
  
    # - name: Docker Push
      # run: docker push brainiak/rtcloud:latest
