name: Make and Push Docker Images to Dockerhub

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "${{secrets.DOCKER_USER}} ${{secrets.DOCKER_PASSWORD}}" > tt.txt
        # echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

    - name: check env
      run: cat tt.txt
